### PR TITLE
Fix livezone reset

### LINKED ISSUE #2604: Live zone message errors
- When I'm in a live zone empty, I have a button to load message but there are no messages, 
 - When I reset the live zone, it keeps alive in my chat menu. The live zone should disappear when I quit the live zone area.

https://user-images.githubusercontent.com/23724509/190526350-63dd352e-6a77-48f8-8255-80d76b974cb1.mov

### PR DESCRIPTION
**Pull request by cesar-cardinale**
- Loading last messages automatically when entering a live zone,
- When reset the live zone, this one is responding again and can be leave when moving away

Closes #2604

### CODE REVIEW

File: front/chat/src/Components/ChatActiveThread.svelte [hunk 1]
```diff
@@ -23,6 +24,7 @@
 
     $: usersListStore = activeThread.getPresenceStore();
     $: meStore = activeThread.getMeStore();
+    $: readyStore = activeThread.getRoomReadyStore();
```
Comment (moufmouf) [inline front/chat/src/Components/ChatActiveThread.svelte:27]:
```suggestion
    const usersListStore = activeThread.getPresenceStore();
    const meStore = activeThread.getMeStore();
    const readyStore = activeThread.getRoomReadyStore();
```

File: pusher/src/Services/XmppClient.ts [hunk 2]
```diff
@@ -282,6 +282,8 @@ export class XmppClient {
         if (xml.getChild("ping")) {
             this.sendPong(xml.getAttr("from"), xml.getAttr("to"), xml.getAttr("id"));
             return false;
+        } else if (xml.getName() === "presence" && xml.getChild("c", "http://jabber.org/protocol/caps")) {
+            return false;
```
Comment (moufmouf) [inline pusher/src/Services/XmppClient.ts:286]: Try moving this to front rather than skipping it in pusher
