### PR TITLE
Fixing enter/leave event not properly sent on adjacent zones

### LINKED ISSUE #1366: Exit "zone" message not triggered when stepping from one "zone" to another
If we have 2 tiles with adjacent "zones" (as defined in https://workadventu.re/map-building/api-room.md#detecting-when-the-user-entersleaves-a-zone), when going from one zone to the other zone, the "leave" event is not triggered.

### PR DESCRIPTION
**Pull request by moufmouf**
On adjacent zones, the zone leave event was not properly triggered when leaving a zone for the zone next to it.
Closes #1366

### CODE REVIEW

File: front/src/Phaser/Game/GameScene.ts [hunk 1]
```diff
@@ -915,9 +915,10 @@ export class GameScene extends DirtyScene {
         });
 
         this.gameMap.onPropertyChange("zone", (newValue, oldValue) => {
-            if (newValue === undefined || newValue === false || newValue === "") {
+            if (oldValue !== undefined && oldValue !== false && oldValue !== "") {
```
Comment (jonnytest1) [inline front/src/Phaser/Game/GameScene.ts:918]: or in short : `!oldValue`

Comment (moufmouf) [reply front/src/Phaser/Game/GameScene.ts]: yup. :+1:
