### PR TITLE
Limiting the number of messages sent while moving

### LINKED ISSUE #137: Minimize the number of messages sent
The number of messages sent when moving (1 per tick) is too high.
As a result, with 30 users moving around, the CPU load hits 100% (on the core running node)

We should do things differently.

Here is how Valve is handling multiplayer movement: https://developer.valvesoftware.com/wiki/Source_Multiplayer_Networking

We could do something a bit similar:

On the client, we send the position only every 200ms (so 5 times per second, that should be enough, we are not a shooter :) ). The position is only sent if the user moved (i.e. if one of `x`, `y`, `direction` and `moving` has been modified). If a message has been sent in the last 200ms, we wait until 200ms finished before sending a new message.
There is one exception: if the user stops moving (by releasing the keys of the keyboard or if a collision happens), we should send the message immediately without waiting 200ms.

On the server, nothing changes, we forward the position.

On the other clients that receive the new position:
At the very moment we receive the "USER_MOVED" message, we know the position of the user lags 200ms behind the position where it should be. So instead of teleporting the player to the new position, we will linearly move it towards the new position over the next 200ms. This is **interpolation**. At the end of the 200ms, we should receive a new "USER_MOVED" message (and we continue interpolating.

For some reason, the next "USER_MOVED" message could be delayed (due to network lag, we could receive the next message 300ms after the previous one and not 200ms for instance). So when the user reaches the position it was supposed to have after 200ms, the user should not stop for 100ms. Instead, we will assume it continues moving in the same direction. This is **extrapolation**.
We will only extrapolate for a short amount of time (let's say no more than 250ms). If we still don't have received a new "USER_MOVED" message, we will assume something went wrong with the player connection and the user should stop moving (while we wait for the next "USER_MOVED" message).
Note: For now, I propose that other players are not subject to physics (so they can go through walls), etc... That should be easier for us. If we see issues, we can fix them later.

TODO:

- [x] Delay sending of position every 200ms
- [x] On the receiving end, store start position, end position, start tick and end tick for every player moving
- [x] Compute interpolation and extrapolation
- [x] Stop extrapolation if too much time is elapsed

### PR DESCRIPTION
**Pull request by moufmouf**
This should help limit the resources spent on the server for managing movement

Closes #137

### CODE REVIEW

File: front/src/Phaser/Game/GameScene.ts [hunk 1]
```diff
@@ -37,12 +39,22 @@ export class GameScene extends Phaser.Scene {
...
     MapUrlFile: string;
     RoomId: string;
     instance: string;
 
+    currentTick: number;
+    lastSentTick: number; // The last tick at which a position was sent.
+    lastMoveEventSent: HasMovedEvent = {
+        direction: '',
+        moving: false,
+        x: -1000,
```
Comment (gparant) [inline front/src/Phaser/Game/GameScene.ts:54]: why `-1000` in the initial variable ?

Comment (moufmouf) [reply front/src/Phaser/Game/GameScene.ts:54]: I need to initiate it to some random value (this avoids me to do a "null" check that is useful only for the first move) and I need to be sure that this will be overwritten when the user is making the first move (so that lastMoveEventSent is different from the next event). By putting x=-1000, I'm sure that lastMoveEventSent != next event sent.
