### PR TITLE
Fixing size of camera on resize

### LINKED ISSUE #1180: Viewport seems to not contain all players when resizing
Open a room with many users.

Use F12 to open close dev-tools. This will resize the viewport at once.
The users I'm sitting next to are not necessarily visible.

It seems the viewport is not always communicated to the pusher (or that the coordinates communicated are the old ones maybe....)

### PR DESCRIPTION
**Pull request by moufmouf**
The size of the Camera after a change in zoom is only computed on the "render" step.
Therefore, we should wait the "render" step to call GameScene.onResize.

Closes #1180

### CODE REVIEW

File: front/src/Phaser/Services/WaScaleManager.ts [hunk 1]
```diff
@@ -3,6 +3,7 @@ import ScaleManager = Phaser.Scale.ScaleManager;
 import {coWebsiteManager} from "../../WebRtc/CoWebsiteManager";
 import type {Game} from "../Game/Game";
 import {ResizableScene} from "../Login/ResizableScene";
+import * as Phaser from "phaser";
```
Comment (Kharhamel) [inline front/src/Phaser/Services/WaScaleManager.ts:6]: A éviter ça. Phaser est déjà injecté dans le contexte js

Comment (moufmouf) [reply front/src/Phaser/Services/WaScaleManager.ts:6]: Ha oui tiens... :+1:
